-
    version: '8.{build}'

    ## -- Git --

    branches:
      only:
      - master
    clone_depth: 1
    skip_non_tags: true
    skip_commits:
      message: '(?i)Update README(\.md)?(\s*)$'

    ## -- Environment --

    configuration: Release
    platform: Any CPU
    matrix:
      fast_finish: true


    ## -- Tool options -- 

    assembly_info:
      patch: true
      file: '**\VersionInfo.*'
      assembly_version: '{version}'
      assembly_file_version: '{version}'
      assembly_informational_version: '{version}'

    nuget:
      account_feed: true
      project_feed: true
      disable_publish_on_pr: true
    
    before_build:
      - nuget restore
    
    build:
      project: LiquidState\LiquidState.csproj
      publish_nuget: true
      include_nuget_references: true
      verbosity: minimal

    ## -- Deployment --

    deploy:
    - provider: NuGet
      api_key:
        secure: SRVDkFc46GEnfXBrnFu7kFml7ozzCAH8thZ5s4gvneVLKo+5QfINtxAB+xSCCQQi
      skip_symbols: true